### ISSUE TITLE
Publish to Ansible Galaxy

### ISSUE THREAD

**Issue by koubas** [alertlogic/al-agents-ansible-playbooks#10]
Hi,

please publish this role for us so we can add it comfortably to our Ansible Galaxy roles requirements file. There is already one clone (blade2005.al-agents) but I'd rather trust your official one.

**Comment by blade2005** [comment]
Heh. Mine probably has test fixes and I should really take it down. 

That being said here is the link to the one under alertlogic org: https://galaxy.ansible.com/alertlogic/al_agents/
