### ISSUE TITLE
autoscaling/imaging variable - override for dynamic play runs

### ISSUE THREAD

**Issue by sparkacus** [alertlogic/al-agents-ansible-playbooks#11]
Hi,

I currently run this role as a dynamic install by including it in our requirements.yml role, but the problem is the 'al_agent_for_autoscaling' and 'al_agent_for_imaging' variables we pass through as role variables are being overridden by the al-agents-ansible-playbooks/vars/main.yml file - I believe this to be the case anyway.

To get around this I have to include the variables as extra-vars when running the playbook, which seems to take precedence, but if I forget it means the AL agent is started/registered.

Would you consider relocating the above variables to al-agents-ansible-playbooks/defaults/main.yml instead?

**Comment by blade2005** [comment]
I'd anticipated it being group/host variables which the overrides work fine from that perspective.

I'm a bit backed up with making changes on this. If you'd like to make a PR I'll be happy to review it. Otherwise it may need to wait until I've got some free cycles to devote to this.

**Comment by muram** [comment]
al_agent_for_autoscaling has been deprecated in #23
