### ISSUE TITLE
Missing Steps for imaging purposes

### ISSUE THREAD

**Issue by tsalingueprofilsoft** [alertlogic/al-agents-ansible-playbooks#8]
Hello Guys ,

Thanks you for your alert logic agent role , I am facing an issue using it maybe you can tell me if I did something wrong or not.

We have a tool that build our AMI (launch an instance , apply role , stop the instance, create the AMI) using ansible and then we launched those AMI in a cloudformation template.

Once you apply the imaging flag, the provisionning is not called at all

https://github.com/alertlogic/al-agents-ansible-playbooks/blob/master/tasks/provision_agent.yml#L10-L15

So once our instances starts the application is not provisionned at all , I don't think this is the right behavior.

I have created a PR : https://github.com/alertlogic/al-agents-ansible-playbooks/pull/7

Can you correct me if something is wrong here ?

**Comment by blade2005** [comment]
I will take a deeper look into the logic behind this to ensure this is correct. In the event we do need to make this change can you rebase against the master. It looks like this fork is missing the most recent commit from today https://github.com/alertlogic/al-agents-ansible-playbooks/commit/218aa38f077234ea331a5fd9f69eb6c620121ffb

**Comment by blade2005** [comment]
Provisioning does need to run but the conditional should be changed from https://github.com/alertlogic/al-agents-ansible-playbooks/blob/master/tasks/provision_agent.yml#L15 to

```
  when: agent_provisioned.stat.exists == false and al_agent_provision_options != "[]"
```
and a conditional added to notify
```
  notify:
    - restart al-agent
    when: al_agent_for_imaging
```

This means we won't need multiple tasks for the minor change.

I haven't tested out that logic but based on web searches this syntax change should be suitable.

**Comment by tsalingueprofilsoft** [comment]
@blade2005 ok so should I do those change on my fork and update my PR or should I leave it to you ?
Also there one flag I don't know his purpose the flag al_agent_for_autoscaling because if I read well the install docs when we do AMI based we need to provision using this command 

```code
/etc/init.d/al-agent provision --key <UNIQUEREGISTRATIONKEY> --inst-type host
```

So for me al_agent_for_autoscaling and al_agent_for_imaging both need the option :

```code
 --inst-type host
```

Am I wrong ?

**Comment by blade2005** [comment]
Please make the changes to your fork and update your PR.

@tsalingueprofilsoft Questions regarding what different flags do for the agent should be directed to AlertLogic support.

**Comment by blade2005** [comment]
For baking the agent into an ami, you should only need to set the al_agent_registration_key to the unique reg key and set al_agent_for_imaging to true.

For normal installation you only need to set al_agent_registration_key

**Comment by tsalingueprofilsoft** [comment]
Ok I will try to do that , 

I was following the instruction of this pdf 
[ESS-Unified Agent Deployment Guide.pdf](https://github.com/alertlogic/al-agents-ansible-playbooks/files/576030/ESS-Unified.Agent.Deployment.Guide.pdf)

Should I trust this file or this url : 

https://docs.alertlogic.com/install/alert-logic-agent-linux.htm

**Comment by blade2005** [comment]
hey @tsalingueprofilsoft that kind of question should be directed to AlertLogic support (support@alertlogic.com).

**Comment by tsalingueprofilsoft** [comment]
Ok I will reach them , thanks for your help .

Let me know when I/You can merge the PR

**Comment by blade2005** [comment]
@tsalingueprofilsoft Were you able to try moving the when: al_agent_for_imaging to the notify part of the task rather than duplicating the entire task?

**Comment by tsalingueprofilsoft** [comment]
Nope It didn't work , I couldn't find an easy and clean way of doing it so right now duplicate the line if the safest choice

**Comment by blade2005** [comment]
I was hoping it would, docs said it should have been able to. Well I'll do a quick test for your pr and merge it today.

**Comment by tsalingueprofilsoft** [comment]
@blade2005 Thank you

**Comment by blade2005** [comment]
#7 merged
